'use strict';
const $=id=>document.getElementById(id);let token=null,backup=null,generated=null,busy=false;
const message=text=>{$('account-message').textContent=text};
async function api(path,method='GET',data){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch('/api/kl/'+path,{method,headers:{...(data?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},...(data?{body:JSON.stringify(data)}:{}),signal:controller.signal,cache:'no-store'});const p=await r.json();if(!r.ok)throw Error(p.error||'Serviço indisponível.');return p}finally{clearTimeout(timer)}}
async function action(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn()}catch(e){message(e.name==='AbortError'?'A conexão demorou. Tente novamente.':e.message)}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);$('register').disabled=!$('understand').checked||!!generated}}
function download(name,text){const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$('understand').addEventListener('change',()=>{$('register').disabled=!$('understand').checked||!!generated});
$('register').addEventListener('click',()=>action(async()=>{if(!$('understand').checked)return;generated=await api('register','POST',{});$('register').textContent='Conta criada';$('new-user').value=generated.username;$('new-password').value=generated.password;$('username').value=generated.username;$('credentials').hidden=false;message('Conta criada. Guarde o acesso antes de fechar esta página.')}));
$('show-password').addEventListener('click',()=>{const show=$('new-password').type==='password';$('new-password').type=show?'text':'password';$('show-password').textContent=show?'Ocultar senha':'Mostrar senha';$('password-full').hidden=!show;$('password-full').textContent=$('new-password').value});
$('copy').addEventListener('click',()=>action(async()=>{await navigator.clipboard.writeText(generated.username);message('Usuário copiado. Cole no campo Usuário do aplicativo.')}));
$('copy-password').addEventListener('click',()=>action(async()=>{await navigator.clipboard.writeText(generated.password);message('Senha copiada. Cole no campo Senha do aplicativo.')}));
$('save-access').addEventListener('click',()=>{if(generated)download('Meu-acesso-KL.txt','Conta KL Play\nUsuário: '+generated.username+'\nSenha: '+generated.password+'\n\nNão compartilhe este arquivo. Quem tem a senha pode acessar e apagar sua conta.\n')});
$('login').addEventListener('submit',e=>{e.preventDefault();action(async()=>{const p=await api('login','POST',{username:$('username').value,password:$('password').value});token=p.token;$('password').value='';backup=await api('profile');$('welcome').textContent=backup.username;$('backup-status').textContent=backup.profile?'Backup do perfil salvo em '+new Date(backup.updated*1000).toLocaleString('pt-BR')+'. Revisão '+backup.revision+'.':'Sua conta está pronta. Entre no aplicativo e envie seu primeiro backup.';$('signed-out').hidden=true;$('signed-in').hidden=false;message('Conta autenticada pelo servidor KL.')} )});
$('export-profile').addEventListener('click',()=>action(async()=>{backup=await api('profile');if(!backup.profile)throw Error('Ainda não existe um backup. Envie pelo aplicativo.');download('KL-perfil-backup.json',JSON.stringify({schema:1,username:backup.username,revision:backup.revision,profile:backup.profile},null,2));message('Cópia baixada. O arquivo contém seu diário; guarde de forma privada.')}));
function exit(){token=null;backup=null;$('signed-in').hidden=true;$('signed-out').hidden=false;message('Você saiu da conta.')}
$('logout').addEventListener('click',()=>action(async()=>{try{await api('logout','POST')}finally{exit()}}));
$('delete-account').addEventListener('click',()=>action(async()=>{if($('delete-confirm').value!=='EXCLUIR')throw Error('Digite EXCLUIR para confirmar.');await api('account','DELETE');exit();message('Conta e backup excluídos do servidor.')}));
